

name: CI - Tests

on:
  push:
    branches:
      - '**'       # cualquier rama...
      - '!main'    # ...excepto main
    tags-ignore:
      - '**'       # nunca en tags

jobs:
  run-tests:
    name: Instalar dependencias y ejecutar tests
    runs-on: ubuntu-latest
    steps:
      - name: 1 · Descargar el código
        uses: actions/checkout@v4

      - name: 2 · Instalar dependencias
        run: npm install

      - name: 3 · Ejecutar tests
        run: npm test
