on:
  push:
    tags:
      - 'v*.*.*' 
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  usar-receta-compartida:
    uses: jp69420/AUY1104-SharedWorkflows/.github/workflows/deply-api.yaml@main
    
    with:
      image-name: demo-api
      image-tag: ${{ github.ref_name }}
      k3s-server-public-ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}
      
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EA2_SSH_PRIVATE_KEY: ${{ secrets.EA2_SSH_PRIVATE_KEY }}